---
title: "Homework 8"
author: "Jacob Dym, Justin Gomez, Paul Harmon"
date: "11/21/2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read Monserud and Marshall (2001) “Time-series analysis of…” All answers to the following should be short even though the paper is long and contains a lot of information. It ends up introducing concepts that we will spend the rest of the semester digging into and does that pretty well. Focus on the statistical methods employed, reasons for using them, and how they discuss their results.

This should be done in groups of up to 3. You will lose 2% if you do not work in a group of 2 and get a bonus of 2% if you work in a group of 3.

1) What do they provide for a reason for removing the quadratic trend? Why do they want to use a trend model with limited flexibility?

-pg 1091 I think under "Removing the time trend"-
The authors of the study are interested in analyzing the variance of the detrended model, so they subtract the time trend for the model (quadratic in this case) and work with the residuals. The goal of detrending the model is to preserve the underlying variation, so limited trend models are preferable

2) How do they determine the order of the trend model from none to quadratic? Are there any potential criticisms of the way they do this? Do not discuss the potential issue with doing these tests without accounting for potential autocorrelation – we know that the SEs would change if these tests were conducted using models that account for autocorrelation.

-pg 1091 end of Removing the time trend-
The authors determined the order of the trend for a model by examining the model residuals with a linear, quadratic, or no trend present. They would then use a procedure such as a t-test to decide between what form to use for a model.

3) Figure 3 contains two ACF plots. Discuss the patterns in the two SACFs (left two panels of Figure 3).

4) Note that their bounds for testing in Figure 3 are different from the formula provided in the book – we will discuss the modification I think they used later. What is the sample size (length of time series!) for the mean douglas-fir and mean western white pine time series. Based on these sample sizes, what cut-offs would you plot on Figure 3 based on the approximate result we discussed in class? How do theirs differ?

5) We discussed four different reasons for doing time series modeling at the beginning of the semester (pages 1 and 2 of lecture notes). Of those four reasons, which one does their use of ARMA models fall into and why? There may be multiple choices that are reasonable here, so the argument you make is important. I am not talking about what you could do with their models, just what they did do with them and their reason for employing them.

6) Use arima.sim to simulate from Delta response AR(2) models for either the mean D or mean W discussed in Table 4 generating the same number of observations as in their time series (see Table 2). You can use a standard deviation for the white noise process of 0.4. This simulation is just concerned with the residual process after removing the trend. Plot a simulated fake time series, the SACF from the fake time series, and compare the results to those that you can find in the paper in Figure 3. How are your results similar or different from their results? Simulate a second series and discuss the differences in your two simulations.

7) Use R to find the roots of your selected AR(2) model based on their published coefficients and note what that tells you about the properties of the AR(2) process under consideration.

